export const TECH_SLUG: Record<string, string> = {
  React: "react",
  "Next.js": "nextdotjs",
  "React Native": "react",
  Redux: "redux",
  "Tailwind CSS": "tailwindcss",
  JavaScript: "javascript",
  TypeScript: "typescript",
  Python: "python",
  "C#": "csharp",
  PHP: "php",
  Java: "java",
  "C++": "cplusplus",
  "Node.js": "nodedotjs",
  "Express.js": "express",
  FastAPI: "fastapi",
  Django: "django",
  Laravel: "laravel",
  OpenAI: "openai",
  Groq: "groq",
  LangChain: "langchain",
  WebSocket: "socketdotio",
  Stripe: "stripe",
  HubSpot: "hubspot",
  PostgreSQL: "postgresql",
  MongoDB: "mongodb",
  "SQL Server": "microsoftsqlserver",
  Firebase: "firebase",
  Docker: "docker",
  Jenkins: "jenkins",
  Git: "git",
  AWS: "amazonaws",
  Expo: "expo",
  IoT: "arduino",
  Puppeteer: "puppeteer",
  Cheerio: "cheerio",
  Lighthouse: "googlelighthouse",
};

export const TECH_COLORS: Record<string, string> = {
  React: "61DAFB",
  "Next.js": "111827",
  "React Native": "61DAFB",
  Redux: "764ABC",
  "Tailwind CSS": "38BDF8",
  JavaScript: "F7DF1E",
  TypeScript: "3178C6",
  Python: "3776AB",
  "C#": "512BD4",
  PHP: "777BB4",
  Java: "E76F00",
  "C++": "00599C",
  "Node.js": "5FA04E",
  "Express.js": "111827",
  FastAPI: "009688",
  Django: "0C4B33",
  Laravel: "FF2D20",
  OpenAI: "10B981",
  Groq: "F5504E",
  LangChain: "10B981",
  WebSocket: "334155",
  Stripe: "635BFF",
  HubSpot: "FF7A59",
  PostgreSQL: "4169E1",
  MongoDB: "47A248",
  "SQL Server": "CC2927",
  Firebase: "FFCA28",
  Docker: "2496ED",
  Jenkins: "D24939",
  Git: "F05032",
  AWS: "FF9900",
  Expo: "111827",
  IoT: "00979D",
};

export function getTechIconUrl(name: string) {
  const slug = TECH_SLUG[name];
  if (!slug) return "";
  const color = TECH_COLORS[name] ?? "64748B";
  return `https://api.iconify.design/simple-icons:${slug}.svg?color=%23${color}`;
}
